### ISSUE TITLE
Error while trying to 'make' mochiweb_xpath

### ISSUE THREAD

**Issue by Nesh108** [retnuh/mochiweb_xpath#4]
Hello, 
I have tried to use this component, but it fails:

==> mochiweb (get-deps)
==> retnuh-mochiweb_xpath-98ec511 (get-deps)
==> mochiweb (compile)
==> retnuh-mochiweb_xpath-98ec511 (compile)
ERROR: git describe --always --tags failed with error: 128
make: *** [compile] Error 1

How can I fix it? 
I am on OS X SL.

Thanks!

**Comment by retnuh** [comment]
I don't know if this is still an issue; I've recently given the project a bit of love, fwiw.  I'm going to close this for now.
